language: node_js
node_js:
  - 14.8.0
cache:
  apt: true
  directories:
      - node_modules      
install:
  - yarn
branches:
  only:
    - master
script:
  - hexo clean
  - hexo generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
